---
- name: Read messages from a kafka topic and act on them
  hosts: all
  ## Define our source for events
  sources:   
    - ansible.eda.kafka:
        host: 10.50.202.51
        port: 9092
        topic: eda-test-events

  ## Define the conditions we are looking for
  rules:
    - name: Say Hello
      #condition: event.body.message == "Ansible is cool"
      #condition: event.body.message == "Create a SNOW"
      condition: event.body is search("Reboot occured and have met requirements to be send to webhook")
      ## Define the action we should take should the condition be met
      action:
        #debug:
        #  msg:
        #    - "{{ event.body.message }}"
        run_job_template:
          #name: respond-kafka-message
          name: AdSales
          organization: WBD-Citrix

